### ISSUE TITLE
rocket.chat not working although no obvious errors in logs

### ISSUE THREAD

**Issue by wurzelbutz** [xavier-hernandez/rocket.chat#1]
Hi

 I downloaded your docker-compose.yml and edited volumes and hostname/IP.
The stack is starting up and there are no obvious erros in the logs.

> rocketchat            | +---------------------------------------+
> rocketchat            | |             SERVER RUNNING            |
> rocketchat            | +---------------------------------------+
> rocketchat            | |                                       |
> rocketchat            | |  Rocket.Chat Version: 4.1.2           |
> rocketchat            | |       NodeJS Version: 12.22.1 - x64   |
> rocketchat            | |      MongoDB Version: 4.2.17          |
> rocketchat            | |       MongoDB Engine: wiredTiger      |
> rocketchat            | |             Platform: linux           |
> rocketchat            | |         Process Port: 3000            |
> rocketchat            | |             Site URL: https://docker  |
> rocketchat            | |     ReplicaSet OpLog: Enabled         |
> rocketchat            | |          Commit Hash: 2aba8d2d82      |
> rocketchat            | |        Commit Branch: HEAD            |
> rocketchat            | |                                       |
> rocketchat            | +---------------------------------------+

When opening https://docker:3000 I get an error that the website is not reachable.
When opening http://docker:3000 I see 3 "loading dots" for about 1 sec and then a login form for about 0,5 sec. after that the page is grey and the browser console is filled with JS errors like 
`Error: Cannot find module '/client/views/setupWizard/SetupWizardRoute.js'`

any ideas?
Thanks,
Wurzelbutz

**Comment by xavier-hernandez** [comment]
Your proxying https://docker ? Does it have a SSL cert? If you are not maybe change the Site URL to http://docker .

**Comment by wurzelbutz** [comment]
no it doesn't.
I also tried with http://docker (in the docker-compose.yml). didn't work either. same problems

**Comment by xavier-hernandez** [comment]
can you try a complete re-install, deleting everything, and try using http://docker ?

**Comment by wurzelbutz** [comment]
same outcome :/
`docker-compose down`
`rm -rf data/ uploads/ hubot/`
`docker-compose up`

docker-compose.yml attached. I changed

- IP
- hostname
- volume locations
[docker-compose.txt](https://github.com/xavier-hernandez/rocket.chat/files/7849473/docker-compose.txt)

**Comment by xavier-hernandez** [comment]
you get this same error, "Error: Cannot find module '/client/views/setupWizard/SetupWizardRoute.js'" ?

docker file looks good

**Comment by wurzelbutz** [comment]
yes there is a whole bunch of errors: ![errors](https://user-images.githubusercontent.com/97356138/149018903-a4f7a357-119e-4e87-adee-59bbae7c87cb.png)

**Comment by xavier-hernandez** [comment]
So I brought up a fresh VM and was somewhat able to reproduce your issue in Firefox. I saw all the errors you pasted but the GUI did popup. It looks like the site URL in the docker compose should be "http://docker:3000". Give it a shot. You might need to start from scratch, just for ease, as I think the URL is stored in the DB or other files.

      - ROOT_URL=http://docker:3000

I never tried to run it locally without a proxy so never ran across the issue.

**Comment by wurzelbutz** [comment]
Hi
thanks a lot for your efforts!
I changed the Root_url to ...:3000 firefox still showed the errors but the setup was working using chrome.
Rocketchat seems to be working now. Thanks!
